export const WS_CONNECTED = "WS_CONNECTED";
export const WS_DISCONNECTED = "WS_DISCONNECTED";
export const WS_ERROR = "WS_ERROR";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_COMPLETE = "GET_USER_COMPLETE";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_ASSETS_REQUEST = "GET_ASSETS_REQUEST";
export const GET_ASSETS_COMPLETE = "GET_ASSETS_COMPLETE";
export const GET_ASSETS_ERROR = "GET_ASSETS_ERROR";
export const GET_DEFAULT_ASSETS_REQUEST = "GET_DEFAULT_ASSETS_REQUEST"
export const GET_DEFAULT_ASSETS_COMPLETE = "GET_DEFAULT_ASSETS_COMPLETE"
export const GET_DEFAULT_ASSETS_ERROR = "GET_DEFAULT_ASSETS_ERROR"